version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
