name: CI/CD to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 権限設定を追加
permissions:
  contents: read
  pull-requests: write # PRへのコメント権限を追加

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install && pnpm build
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # 組織IDを追加
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # プロジェクトIDを追加
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--yes'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # 組織IDを追加
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # プロジェクトIDを追加
